import "server-only";

import type { SourceRegistryEntry } from "./types";

const publicApiNote = "Use official public endpoint only; preserve source identifiers and access dates.";
const noPortalNote = "Patient portals/EHR systems are excluded; future FHIR/EHR access requires separate authorization, consent, security, and legal review.";

export const sourceRegistry: SourceRegistryEntry[] = [
  { providerId: "pubmed", displayName: "PubMed / NCBI E-utilities", category: "literature", accessMethod: "official_api", publicAccessStatus: "public_open", termsReviewRequired: false, supportsLiveQuery: true, supportsBulkDownload: false, storesRawDataAllowed: true, claimPromotionAllowed: "yes_after_review", notes: [publicApiNote, "Optional server-only NCBI_API_KEY may improve rate limits."] },
  { providerId: "pmc", displayName: "PubMed Central / PMC", category: "literature", accessMethod: "official_api", publicAccessStatus: "public_open", termsReviewRequired: false, supportsLiveQuery: false, supportsBulkDownload: true, storesRawDataAllowed: true, claimPromotionAllowed: "yes_after_review", notes: ["Registry only in this phase."] },
  { providerId: "europepmc", displayName: "Europe PMC", category: "literature", accessMethod: "official_api", publicAccessStatus: "public_open", termsReviewRequired: true, supportsLiveQuery: false, supportsBulkDownload: false, storesRawDataAllowed: true, claimPromotionAllowed: "yes_after_review", notes: ["Registered for later implementation after terms review."] },
  { providerId: "crossref", displayName: "Crossref", category: "literature", accessMethod: "official_api", publicAccessStatus: "public_open", termsReviewRequired: true, supportsLiveQuery: false, supportsBulkDownload: false, storesRawDataAllowed: true, claimPromotionAllowed: "candidate_only", notes: ["Registered for DOI metadata; not biomedical evidence by itself."] },
  { providerId: "semantic-scholar", displayName: "Semantic Scholar", category: "literature", accessMethod: "official_api", publicAccessStatus: "public_with_api_key", termsReviewRequired: true, supportsLiveQuery: false, supportsBulkDownload: false, storesRawDataAllowed: false, claimPromotionAllowed: "candidate_only", notes: ["Registered only; API key/terms review required."] },
  { providerId: "biorxiv-medrxiv", displayName: "bioRxiv / medRxiv", category: "literature", accessMethod: "official_api", publicAccessStatus: "public_open", termsReviewRequired: true, supportsLiveQuery: false, supportsBulkDownload: false, storesRawDataAllowed: true, claimPromotionAllowed: "candidate_only", notes: ["Preprints require review and should not be promoted as settled evidence."] },
  { providerId: "google-scholar", displayName: "Google Scholar", category: "literature", accessMethod: "manual_review_required", publicAccessStatus: "not_implemented", termsReviewRequired: true, supportsLiveQuery: false, supportsBulkDownload: false, storesRawDataAllowed: false, claimPromotionAllowed: "no", notes: ["No scraping-safe official public API; not implemented."] },

  { providerId: "clinicaltrials", displayName: "ClinicalTrials.gov API v2", category: "clinical_trials", accessMethod: "official_api", publicAccessStatus: "public_open", termsReviewRequired: false, supportsLiveQuery: true, supportsBulkDownload: false, storesRawDataAllowed: true, claimPromotionAllowed: "yes_after_review", notes: [publicApiNote] },
  { providerId: "eu-ctr-ctis", displayName: "EU Clinical Trials Register / CTIS", category: "clinical_trials", accessMethod: "manual_review_required", publicAccessStatus: "not_implemented", termsReviewRequired: true, supportsLiveQuery: false, supportsBulkDownload: false, storesRawDataAllowed: false, claimPromotionAllowed: "candidate_only", notes: ["Registry only unless permitted API/source is confirmed."] },
  { providerId: "who-ictrp", displayName: "WHO ICTRP", category: "clinical_trials", accessMethod: "manual_review_required", publicAccessStatus: "not_implemented", termsReviewRequired: true, supportsLiveQuery: false, supportsBulkDownload: false, storesRawDataAllowed: false, claimPromotionAllowed: "candidate_only", notes: ["Registry/manual review only until permitted API access is confirmed."] },

  { providerId: "openfda-label", displayName: "openFDA Drug Labels", category: "drug_label", accessMethod: "official_api", publicAccessStatus: "public_open", termsReviewRequired: false, supportsLiveQuery: true, supportsBulkDownload: false, storesRawDataAllowed: true, claimPromotionAllowed: "yes_after_review", notes: [publicApiNote] },
  { providerId: "openfda-faers", displayName: "openFDA Drug Adverse Events / FAERS", category: "drug_safety", accessMethod: "official_api", publicAccessStatus: "public_open", termsReviewRequired: false, supportsLiveQuery: true, supportsBulkDownload: false, storesRawDataAllowed: true, claimPromotionAllowed: "candidate_only", notes: ["Adverse-event records are signals only; no causal claims."] },
  { providerId: "openfda-enforcement", displayName: "openFDA Drug Enforcement / Recalls", category: "regulatory", accessMethod: "official_api", publicAccessStatus: "public_open", termsReviewRequired: false, supportsLiveQuery: true, supportsBulkDownload: false, storesRawDataAllowed: true, claimPromotionAllowed: "candidate_only", notes: [publicApiNote] },
  { providerId: "openfda-ndc", displayName: "openFDA NDC Directory", category: "drug_label", accessMethod: "official_api", publicAccessStatus: "public_open", termsReviewRequired: false, supportsLiveQuery: true, supportsBulkDownload: false, storesRawDataAllowed: true, claimPromotionAllowed: "candidate_only", notes: [publicApiNote] },
  { providerId: "openfda-drugsfda", displayName: "openFDA Drugs@FDA", category: "regulatory", accessMethod: "official_api", publicAccessStatus: "public_open", termsReviewRequired: false, supportsLiveQuery: true, supportsBulkDownload: false, storesRawDataAllowed: true, claimPromotionAllowed: "candidate_only", notes: [publicApiNote] },
  { providerId: "openfda-device", displayName: "openFDA Device Endpoints", category: "regulatory", accessMethod: "official_api", publicAccessStatus: "public_open", termsReviewRequired: false, supportsLiveQuery: false, supportsBulkDownload: false, storesRawDataAllowed: true, claimPromotionAllowed: "candidate_only", notes: ["Registered for later device use cases."] },
  { providerId: "fda-drugsfda-files", displayName: "FDA Drugs@FDA Downloadable Files", category: "regulatory", accessMethod: "downloadable_dataset", publicAccessStatus: "public_open", termsReviewRequired: true, supportsLiveQuery: false, supportsBulkDownload: true, storesRawDataAllowed: true, claimPromotionAllowed: "yes_after_review", notes: ["Registry only in this phase."] },
  { providerId: "fda-orange-book", displayName: "FDA Orange Book Downloadable Files", category: "regulatory", accessMethod: "downloadable_dataset", publicAccessStatus: "public_open", termsReviewRequired: true, supportsLiveQuery: false, supportsBulkDownload: true, storesRawDataAllowed: true, claimPromotionAllowed: "yes_after_review", notes: ["Registry only in this phase."] },
  { providerId: "fda-purple-book", displayName: "FDA Purple Book", category: "regulatory", accessMethod: "official_public_page", publicAccessStatus: "public_open", termsReviewRequired: true, supportsLiveQuery: false, supportsBulkDownload: true, storesRawDataAllowed: true, claimPromotionAllowed: "yes_after_review", notes: ["Registry only pending file/API confirmation."] },
  { providerId: "fda-rss", displayName: "FDA Press Announcements / RSS", category: "news_rss", accessMethod: "rss_feed", publicAccessStatus: "public_open", termsReviewRequired: false, supportsLiveQuery: true, supportsBulkDownload: false, storesRawDataAllowed: true, claimPromotionAllowed: "candidate_only", notes: ["News/media signal only, not scientific evidence."] },
  { providerId: "fda-medwatch-rss", displayName: "FDA MedWatch RSS / Safety Alerts", category: "news_rss", accessMethod: "rss_feed", publicAccessStatus: "public_open", termsReviewRequired: false, supportsLiveQuery: true, supportsBulkDownload: false, storesRawDataAllowed: true, claimPromotionAllowed: "candidate_only", notes: ["Safety signal/news only; requires review."] },
  { providerId: "dailymed", displayName: "DailyMed SPL API", category: "drug_label", accessMethod: "official_api", publicAccessStatus: "public_open", termsReviewRequired: false, supportsLiveQuery: true, supportsBulkDownload: false, storesRawDataAllowed: true, claimPromotionAllowed: "yes_after_review", notes: [publicApiNote] },

  { providerId: "cdc-wonder", displayName: "CDC WONDER", category: "epidemiology", accessMethod: "official_api", publicAccessStatus: "public_open", termsReviewRequired: true, supportsLiveQuery: false, supportsBulkDownload: false, storesRawDataAllowed: true, claimPromotionAllowed: "yes_after_review", notes: ["Structured stub only; WONDER XML/API query design deferred."] },
  { providerId: "cdc-socrata", displayName: "CDC data.cdc.gov Socrata APIs", category: "public_dataset", accessMethod: "official_api", publicAccessStatus: "public_open", termsReviewRequired: true, supportsLiveQuery: true, supportsBulkDownload: false, storesRawDataAllowed: true, claimPromotionAllowed: "candidate_only", notes: ["Generic dataset metadata query only."] },
  { providerId: "cdc-rss", displayName: "CDC Newsroom / RSS", category: "news_rss", accessMethod: "rss_feed", publicAccessStatus: "public_open", termsReviewRequired: false, supportsLiveQuery: true, supportsBulkDownload: false, storesRawDataAllowed: true, claimPromotionAllowed: "candidate_only", notes: ["News/media signal only."] },
  { providerId: "seer-nci", displayName: "SEER / NCI Public Cancer Statistics", category: "epidemiology", accessMethod: "manual_review_required", publicAccessStatus: "requires_free_account_or_license", termsReviewRequired: true, supportsLiveQuery: false, supportsBulkDownload: false, storesRawDataAllowed: false, claimPromotionAllowed: "candidate_only", notes: ["Registry only; access terms/data agreement may apply."] },
  { providerId: "us-cancer-statistics", displayName: "US Cancer Statistics", category: "epidemiology", accessMethod: "manual_review_required", publicAccessStatus: "requires_free_account_or_license", termsReviewRequired: true, supportsLiveQuery: false, supportsBulkDownload: false, storesRawDataAllowed: false, claimPromotionAllowed: "candidate_only", notes: ["Registry only if access requires SEER*Stat/data agreement."] },
  { providerId: "who-gho", displayName: "WHO Global Health Observatory / Athena API", category: "global_health", accessMethod: "official_api", publicAccessStatus: "public_open", termsReviewRequired: true, supportsLiveQuery: true, supportsBulkDownload: false, storesRawDataAllowed: true, claimPromotionAllowed: "candidate_only", notes: ["Global/public-health candidates only; US focus requires filtering."] },
  { providerId: "owid-health", displayName: "Our World in Data Health Datasets", category: "public_dataset", accessMethod: "downloadable_dataset", publicAccessStatus: "public_open", termsReviewRequired: true, supportsLiveQuery: false, supportsBulkDownload: true, storesRawDataAllowed: true, claimPromotionAllowed: "candidate_only", notes: ["Registry only pending dataset/license review."] },

  { providerId: "gdc", displayName: "NCI GDC API", category: "genomics", accessMethod: "official_api", publicAccessStatus: "public_open", termsReviewRequired: true, supportsLiveQuery: true, supportsBulkDownload: false, storesRawDataAllowed: true, claimPromotionAllowed: "candidate_only", notes: ["Public open-access metadata only; no controlled data."] },
  { providerId: "cbioportal", displayName: "cBioPortal Public API", category: "genomics", accessMethod: "official_api", publicAccessStatus: "public_open", termsReviewRequired: true, supportsLiveQuery: false, supportsBulkDownload: false, storesRawDataAllowed: true, claimPromotionAllowed: "candidate_only", notes: ["Registry only pending terms review."] },
  { providerId: "geo", displayName: "GEO / NCBI Entrez GEO", category: "genomics", accessMethod: "official_api", publicAccessStatus: "public_open", termsReviewRequired: true, supportsLiveQuery: false, supportsBulkDownload: false, storesRawDataAllowed: true, claimPromotionAllowed: "candidate_only", notes: ["Registry only in this phase."] },
  { providerId: "dbgap", displayName: "dbGaP", category: "licensed_or_restricted", accessMethod: "manual_review_required", publicAccessStatus: "restricted_or_licensed", termsReviewRequired: true, supportsLiveQuery: false, supportsBulkDownload: false, storesRawDataAllowed: false, claimPromotionAllowed: "no", notes: ["Controlled data must not be accessed in this phase."] },
  { providerId: "tcga-gdc-public", displayName: "TCGA via GDC Public Metadata", category: "genomics", accessMethod: "official_api", publicAccessStatus: "public_open", termsReviewRequired: true, supportsLiveQuery: false, supportsBulkDownload: false, storesRawDataAllowed: true, claimPromotionAllowed: "candidate_only", notes: ["Open metadata only; controlled data excluded."] },

  { providerId: "rxnorm", displayName: "RxNorm API", category: "terminology", accessMethod: "official_api", publicAccessStatus: "public_open", termsReviewRequired: false, supportsLiveQuery: true, supportsBulkDownload: false, storesRawDataAllowed: true, claimPromotionAllowed: "candidate_only", notes: [publicApiNote] },
  { providerId: "umls", displayName: "UMLS API", category: "terminology", accessMethod: "licensed_api", publicAccessStatus: "requires_free_account_or_license", termsReviewRequired: true, supportsLiveQuery: false, supportsBulkDownload: false, storesRawDataAllowed: false, claimPromotionAllowed: "candidate_only", notes: ["Requires license/account and server-only API key."] },
  { providerId: "mesh", displayName: "MeSH via NCBI", category: "terminology", accessMethod: "official_api", publicAccessStatus: "public_open", termsReviewRequired: false, supportsLiveQuery: false, supportsBulkDownload: false, storesRawDataAllowed: true, claimPromotionAllowed: "candidate_only", notes: ["Registry only; can share NCBI helper later."] },
  { providerId: "medlineplus", displayName: "MedlinePlus", category: "patient_education_public", accessMethod: "official_api", publicAccessStatus: "public_open", termsReviewRequired: false, supportsLiveQuery: true, supportsBulkDownload: false, storesRawDataAllowed: true, claimPromotionAllowed: "candidate_only", notes: [publicApiNote, noPortalNote] },
  { providerId: "medlineplus-connect", displayName: "MedlinePlus Connect", category: "patient_education_public", accessMethod: "official_api", publicAccessStatus: "public_open", termsReviewRequired: false, supportsLiveQuery: false, supportsBulkDownload: false, storesRawDataAllowed: true, claimPromotionAllowed: "candidate_only", notes: [noPortalNote] },
  { providerId: "icd-snomed", displayName: "ICD / SNOMED", category: "terminology", accessMethod: "manual_review_required", publicAccessStatus: "restricted_or_licensed", termsReviewRequired: true, supportsLiveQuery: false, supportsBulkDownload: false, storesRawDataAllowed: false, claimPromotionAllowed: "candidate_only", notes: ["Registry only unless license/access is clear."] },

  { providerId: "nih-rss", displayName: "NIH News RSS", category: "news_rss", accessMethod: "rss_feed", publicAccessStatus: "public_open", termsReviewRequired: false, supportsLiveQuery: true, supportsBulkDownload: false, storesRawDataAllowed: true, claimPromotionAllowed: "candidate_only", notes: ["News/media signal only."] },
  { providerId: "gdelt", displayName: "GDELT Public APIs", category: "news_rss", accessMethod: "official_api", publicAccessStatus: "public_open", termsReviewRequired: true, supportsLiveQuery: true, supportsBulkDownload: false, storesRawDataAllowed: true, claimPromotionAllowed: "candidate_only", notes: ["Media signal candidate only, not scientific evidence."] },
  { providerId: "company-ir-rss", displayName: "Company Investor Relations RSS / Press Releases", category: "market_company_public", accessMethod: "rss_feed", publicAccessStatus: "not_implemented", termsReviewRequired: true, supportsLiveQuery: false, supportsBulkDownload: false, storesRawDataAllowed: false, claimPromotionAllowed: "candidate_only", notes: ["Only if permitted by robots/terms; no paywalled scraping."] },
  { providerId: "sec-edgar", displayName: "SEC EDGAR Company Filings", category: "market_company_public", accessMethod: "official_api", publicAccessStatus: "public_open", termsReviewRequired: true, supportsLiveQuery: false, supportsBulkDownload: false, storesRawDataAllowed: true, claimPromotionAllowed: "candidate_only", notes: ["Registry only for later company/market signals."] },
];

export function getRegistryEntry(providerId: string) {
  return sourceRegistry.find((entry) => entry.providerId === providerId);
}
